(defvar *snomed*)
(defvar *snomed-path* "~/Desktop/snomed/snomedct_us.owl")
(defun setup-disease-work ()
  (setq *snomed* (load-ontology *snomed-path*))
  (setq *default-kb* *snomed*)
  (threads:make-thread  (lambda()
			  (check-ontology *snomed* :classify t :reasoner :factpp)
			  (print "Classified")))
  (threads:make-thread  (lambda()
			  (restore-umls-api-call-cache)
			  (print "Cache restored")))
  (threads:make-thread  (lambda()
			  (rdfs-labels *snomed*)
			  (print "Labels"))))
