(defun run-program-string->string (executable switches input &key wd)
  (let ((process (sys::run-program executable switches :directory wd)))
    (write-string input (sys::process-input process))
    (close (sys::process-input process))
    (let ((error (with-output-to-string (s)
		   (loop for line = (read-line (sys::process-error process) nil :eof)
		       until (eq line :eof)
		       do (write-line line s)))))
      (let ((output (with-output-to-string (s)
		      (loop for line = (read-line (sys::process-output process) nil :eof)
			    until (eq line :eof)
			    do (write-line line s)))))
	(values output error)))))

