---
# This is an Ansible playbook specifying the instructions for deploying the lsw box.
# retry with "vagrant --verbose provision --provision-with resume" if there's a problem 

- hosts: all
  user: vagrant
  gather_facts: no

  tasks:

    # factored out so that they can be shared with the bfo-theory box build
    - include: lsw-tasks.yml


